# Generated by Django 5.2.4 on 2025-08-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='donador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.donador'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.ubicacion'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.zona'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.sucursal'),
        ),
    ]
