# Generated by Django 5.2.3 on 2025-07-03 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
        ('solicitudes', '0002_alter_historialdonacion_donador_and_more'),
        ('usuarios', '0002_donador_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='donador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.donador'),
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Donador',
        ),
        migrations.DeleteModel(
            name='Receptor',
        ),
    ]
