# Generated by Django 5.2.3 on 2025-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
            ],
        ),
    ]
