# Generated by Django 5.2.3 on 2025-07-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_donador_receptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
