# Generated by Django 5.2.4 on 2025-07-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_administrador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='nombre',
        ),
    ]
