# Generated by Django 5.2.3 on 2025-07-03 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=20)),
                ('donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.donador')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.publicacion')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.receptor')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.publicacion')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.receptor')),
            ],
        ),
    ]
