# Generated by Django 5.2.4 on 2025-07-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donaciones', '0002_initial'),
        ('usuarios', '0001_initial'),

    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
