# Generated by Django 5.2.4 on 2025-08-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donaciones', '0002_initial'),
        ('solicitudes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialdonacion',
            name='donador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.donador'),
        ),
        migrations.AddField(
            model_name='historialdonacion',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.publicacion'),
        ),
        migrations.AddField(
            model_name='historialdonacion',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.receptor'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.publicacion'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.receptor'),
        ),
    ]
