# Generated by Django 5.2.3 on 2025-07-03 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('usuarios', '0002_donador_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdonacion',
            name='donador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.donador'),
        ),
        migrations.AlterField(
            model_name='historialdonacion',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.receptor'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.receptor'),
        ),
    ]
